export const SET_AUTHENTICATION = "SET_AUTHENTICATION";

export const SET_COMPONENTS_VISIBILITY = "SET_COMPONENTS_VISIBILITY";

export const ADD_FLASH_MESSAGE = "ADD_FLASH_MESSAGE";
export const DELETE_FLASH_MESSAGE = "DELETE_FLASH_MESSAGE";

export const SET_MODAL_STATE = "SET_MODAL_STATE";
export const MODAL_UNLOAD = "MODAL_UNLOAD";

export const GET_ERRORS = "GET_ERRORS";

export const ADD_SKILL = "ADD_SKILL";
export const FETCH_SKILLS = "FETCH_SKILLS";
export const DELETE_SKILL = "DELETE_SKILL";
export const UPDATE_SKILL = "UPDATE_SKILL";
export const SKILLS_UNLOAD = "SKILLS_UNLOAD";

export const ADD_WORK = "ADD_WORK";
export const FETCH_WORKS = "FETCH_WORKS";
export const DELETE_WORK = "DELETE_WORK";
export const UPDATE_WORK = "UPDATE_WORK";
export const WORKS_UNLOAD = "WORKS_UNLOAD";
